services:
  # Main Go orchestration service
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - api-network
    depends_on:
      - redis
    environment:
      - RUNNER_TIMEOUT=20
      - MAX_REQUEST_SIZE=102400
      - REDIS_URL=redis:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - api-network
    restart: unless-stopped

  golang-runner:
    build:
      context: ./runners/golang
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - api-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50M
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    environment:
      - MAX_EXECUTION_TIME=5

  javascript-runner:
    build:
      context: ./runners/javascript
      dockerfile: Dockerfile
    networks:
      - api-network
    ports:
      - "8002:8002"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50M
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    environment:
      - MAX_EXECUTION_TIME=5

  typescript-runner:
    build:
      context: ./runners/typescript
      dockerfile: Dockerfile
    networks:
      - api-network
    ports:
      - "8003:8003"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50M
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    environment:
      - MAX_EXECUTION_TIME=20

  python-runner:
    build:
      context: ./runners/python
      dockerfile: Dockerfile
    networks:
      - api-network
    ports:
      - "8004:8004"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50M
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    environment:
      - MAX_EXECUTION_TIME=5

networks:
  api-network:
    driver: bridge

volumes:
  redis-data:
